.TH "Dokumentacja katalogu build/CMakeFiles/3.0.2/CompilerIdC" 3 "Pn, 11 sty 2016" "Version 15.1" "RivMix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu build/CMakeFiles/3.0.2/CompilerIdC \- 
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBCMakeCCompilerId\&.c\fP"
.br
.in -1c
