.TH "GridDispersion" 3 "Pn, 11 sty 2016" "Version 15.1" "RivMix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GridDispersion \- Klasa Przygotowujaca siatke do symulacji\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grid\&.h>\fP
.PP
Dziedziczy \fBGrid\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBGridDispersion\fP ()"
.br
.RI "\fIKonstruktor\&. \fP"
.ti -1c
.RI "int \fBReadData\fP (map< int, \fBPoint\fP > &PointMap, const string &file, \fBSimulationParameters\fP &sym_param)"
.br
.in -1c
.SS "Dodatkowe Dziedziczone Składowe"
.SH "Opis szczegółowy"
.PP 
Klasa Przygotowujaca siatke do symulacji\&. 

Zawiera funkcje potrzebne do przgotowania siatki, gdy z pliku wczytywane sa wspolrzedne pktow przeplywu i wartosci wspolczynnikow dyspersji, a skladowe predkosci sa stale na calej siatce\&. 
.PP
Definicja w linii 258 pliku grid\&.h\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "GridDispersion::GridDispersion ()\fC [inline]\fP"

.PP
Konstruktor\&. Tworzy obiekt \fBGrid\fP Dispersion 
.PP
Definicja w linii 264 pliku grid\&.h\&.
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "int GridDispersion::ReadData (map< int, \fBPoint\fP > & PointMap, const string & file, \fBSimulationParameters\fP & sym_param)\fC [virtual]\fP"
Wczytywania dane z pliku wejsciowego do mapy punktow 
.PP
\fBParametry:\fP
.RS 4
\fIPointMap\fP - referencja do Mapy Punktow 
.br
\fIfile\fP - nazwa pliku z danymi 
.br
\fIsym_param\fP - obiekt z parametrami symulacji 
.RE
.PP

.PP
Reimplementowana z \fBGrid\fP\&.
.PP
Definicja w linii 726 pliku grid\&.cpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla RivMix\&.
