.TH "main.cpp" 3 "Pn, 11 sty 2016" "Version 15.1" "RivMix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'simulation\&.h'\fP
.br
\fC#include 'comments\&.h'\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definicja w linii 41 pliku main\&.cpp\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla RivMix\&.
