.TH "netheatflux.h" 3 "Pn, 11 sty 2016" "Version 15.1" "RivMix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netheatflux.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBNetHeatFlux\fP"
.br
.RI "\fIKlasa do obliczen członu źródłowego wyminay ciepla z atmosfera\&. \fP"
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla RivMix\&.
