.TH "param.cpp" 3 "Pn, 11 sty 2016" "Version 15.1" "RivMix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
param.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'param\&.h'\fP
.br
\fC#include 'comments\&.h'\fP
.br
\fC#include <algorithm>\fP
.br

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla RivMix\&.
