.TH "SADI2" 3 "Pn, 11 sty 2016" "Version 15.1" "RivMix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SADI2 \- Schemat naprzemiennych kierunkow ADI \&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scheme\&.h>\fP
.PP
Dziedziczy \fBSScheme\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBSADI2\fP ()"
.br
.RI "\fIKonstruktor\&. \fP"
.ti -1c
.RI "void \fBComputeConcentration\fP (map< int, \fBPoint\fP > &PointMap)"
.br
.RI "\fIOblicza koncentracje uzywajac schamatu ADI2\&. \fP"
.ti -1c
.RI "void \fBGetFactors\fP (\fBPoint\fP *p, const double &CAx, const double &CAy, const double &CDx, const double &CDxy, const double &CDy, const vector< int > &flag)"
.br
.in -1c
.SS "Dodatkowe Dziedziczone Składowe"
.SH "Opis szczegółowy"
.PP 
Schemat naprzemiennych kierunkow ADI \&. 

Zawiera metody potrzebane do rozwiazania rownania transportu metoda ADI\&. 
.PP
Definicja w linii 331 pliku scheme\&.h\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "SADI2::SADI2 ()\fC [inline]\fP"

.PP
Konstruktor\&. Tworzy schemat do rozwiazywania rownania transporu metoda ADI 
.PP
Definicja w linii 339 pliku scheme\&.h\&.
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void SADI2::ComputeConcentration (map< int, \fBPoint\fP > & PointMap)\fC [virtual]\fP"

.PP
Oblicza koncentracje uzywajac schamatu ADI2\&. Oblicza koncentracje w daneym kroku uzywajac metody ADI2 (rozni sie tym od ADI1 ze ma inaczej jest podzielona na dwa 'pdkroki' czasowe) 
.PP
\fBParametry:\fP
.RS 4
\fIPointMap\fP - mapa punktow 
.RE
.PP

.PP
Reimplementowana z \fBSScheme\fP\&.
.PP
Definicja w linii 1699 pliku scheme\&.cpp\&.
.SS "void SADI2::GetFactors (\fBPoint\fP * p, const double & CAx, const double & CAy, const double & CDx, const double & CDxy, const double & CDy, const vector< int > & flag)\fC [virtual]\fP"
Odpowiedzilan za wyznaczenie czynnikow (a, b, c, d, e, f, g, h, i) i (fa, fb, fc, fd, fe, ff, fg, fh, fi) w rowenanie transportu dal zadanego pkt w ktorym obliczana jest koncentracja dla schemtu ADI2
.PP
\fBParametry:\fP
.RS 4
\fI*p\fP - pkt dla ktorego wyznaczane sa czynniki 
.br
\fICAx\fP - adwekcyjna liczba Couranta w kieruynku x 
.br
\fICAy\fP - adwekcyjna liczba Couranta w kieruynku y 
.br
\fICDx\fP - dyfuzyjna liczba Couranta w kieruynku x 
.br
\fICDxy\fP - dyfuzyjna liczba Couranta w kieruynku xy 
.br
\fICDy\fP - dyfuzyjna liczba Couranta w kieruynku y 
.RE
.PP

.PP
Reimplementowana z \fBSScheme\fP\&.
.PP
Definicja w linii 1894 pliku scheme\&.cpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla RivMix\&.
