.TH "scheme_new_bezQ.cpp" 3 "Pn, 11 sty 2016" "Version 15.1" "RivMix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheme_new_bezQ.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'scheme\&.h'\fP
.br
\fC#include 'grid\&.h'\fP
.br
\fC#include 'comments\&.h'\fP
.br
\fC#include 'param\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <algorithm>\fP
.br

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla RivMix\&.
