.TH "tensor.h" 3 "Pn, 11 sty 2016" "Version 15.1" "RivMix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tensor.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'point\&.h'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBDTensor\fP"
.br
.RI "\fIKlasa podstawowa tensora dyspersji\&. \fP"
.ti -1c
.RI "class \fBDFischer\fP"
.br
.RI "\fIKlasa tensora dyspersji\&. \fP"
.ti -1c
.RI "class \fBDFischer2\fP"
.br
.RI "\fIKlasa tensora dyspersji\&. \fP"
.ti -1c
.RI "class \fBDVector\fP"
.br
.RI "\fIKlasa tensora dyspersji\&. \fP"
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla RivMix\&.
